#!/bin/sh
#cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
source $CFDEM_SRC_DIR/lagrangian/cfdemParticle/etc/functions.sh

#- define variables
casePath="$(dirname "$(readlink -f ${BASH_SOURCE[0]})")"
cd $casePath/CFD
cleanCase
#rm $casePath/CFD/shrink*.dat
#rm $casePath/CFD/rmass*.dat
rm $casePath/log*
#rm $casePath/run_error.log
#cp -R 0/Org/p 0/p
#cp -R 0/Org/U 0/U
#cp -R 0/Org/Us 0/Us
#cp -R 0/Org/phiIB 0/phiIB
#cp -R 0/Org/voidfraction 0/voidfraction

rm -R $casePath/DEM/post
mkdir $casePath/DEM/post
mkdir $casePath/DEM/post/restart
#cd $casePath/DEM/post/restart 
#touch liggghts.restart

#cd $casePath
#rm changeOfCO2-3
#rm O2_output_2
#rm rhogas_output-2
#rm pmass_file_4
#rm O2mass_file_4
#rm CO2mass-output-4


# ----------------------------------------------------------------- end-of-file
