#!/bin/bash
#PBS -o fb.out
#PBS -V
#PBS -k oe
#PBS -j oe
#PBS -l nodes=1:ppn=4
#PBS -l walltime=24:00:00
#PBS -m ae
#PBS -M mustafa_efe.kinaci@jku.at

source ~/.bashrc
source /apps/openfoam-4.0/OpenFOAM-4.x-version-4.0/etc/bashrc
source $HOME/CFDEM/CFDEMcoupling/etc/bashrc
module add icc gcc

caseDir=$HOME/CFDEM/CFDEMcoupling/tutorials/cfdemSolverRhoPimpleChem/test_case
cd $caseDir

./Allrun.sh
